// <auto-generated />
using BusinessLookup.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessLookup.Migrations
{
    [DbContext(typeof(BusinessLookupContext))]
    [Migration("20200413090254_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessLookup.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Established")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Description = "We sell tom foolery items.",
                            Established = "2004",
                            Name = "Hooligans",
                            Owner = "John"
                        },
                        new
                        {
                            BusinessId = 2,
                            Description = "We sell golfing equipment and more.",
                            Established = "1993",
                            Name = "Golf N Stuff",
                            Owner = "Ernesto"
                        },
                        new
                        {
                            BusinessId = 3,
                            Description = "We sell the latest tech cell phones.",
                            Established = "2007",
                            Name = "Phones and More",
                            Owner = "George"
                        },
                        new
                        {
                            BusinessId = 4,
                            Description = "We sell the gnarliest surfboards.",
                            Established = "1978",
                            Name = "Surfboards R Us",
                            Owner = "Andy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
